return {
  system = {
    hostname = "basaltos-repo",
    timezone = "UTC",
    locale = "en_US.UTF-8",
    keymap = "us",
  },

  packages = {
    pacman = {
      "base",
      "linux",
      "linux-firmware",
      "sudo",
      "openssh",
      "git",
      "rsync",
      "jq",
      "pacman-contrib",
      "docker",
      "docker-compose",
      "nginx",
      "certbot",
      "basalt-mirrorlist",
    },
    aur = {},
    nix = {},
  },

  services = {
    enable = {
      "sshd",
      "docker",
    },
    disable = {},
  },

  files = {
    managed = {
      {
        path = "/etc/tmpfiles.d/basaltos-repo.conf",
        mode = "0644",
        content = [[
d /srv/basaltos 0755 root root - -
d /srv/basaltos/repo 0755 root root - -
d /srv/basaltos/repo/stable 0755 root root - -
d /srv/basaltos/repo/stable/x86_64 0755 root root - -
d /srv/basaltos/repo/staging 0755 root root - -
d /srv/basaltos/repo/staging/x86_64 0755 root root - -
f /srv/basaltos/repo/healthz 0644 root root - ok
]],
      },
      {
        path = "/srv/basaltos/repo/docker-compose.yml",
        mode = "0644",
        content = [[
services:
  basaltos-repo:
    image: nginx:alpine
    container_name: basaltos-repo
    restart: unless-stopped
    volumes:
      - /srv/basaltos/repo:/usr/share/nginx/html:ro
    expose:
      - "80"
]],
      },
      {
        path = "/etc/pacman.d/basalt-mirrorlist",
        mode = "0644",
        content = [[
## BasaltOS pacman repository mirrors
Server = https://repo.basaltos.dev/stable/$arch
# Server = https://repo.basaltos.dev/staging/$arch
]],
      },
      {
        path = "/etc/pacman.conf.d/basalt.conf",
        mode = "0644",
        content = [[
[basalt]
Include = /etc/pacman.d/basalt-mirrorlist
]],
      },
      {
        path = "/etc/basalt/repo-hosting-status.md",
        mode = "0644",
        content = [[
# BasaltOS Repo Host Status

This host can serve static repo files from /srv/basaltos/repo.

Still required before real users install from it:
- signed package artifacts
- basalt.db and basalt.files generated by repo-add
- basalt.db.sig and basalt.files.sig
- release manifest and promotion review
- publication sync from staging to stable
- public DNS and Nginx Proxy Manager TLS
- public health checks
]],
      },
    },
  },
}

